// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: proto/statistics.proto

package statisticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsRequest) Reset() {
	*x = UserStatsRequest{}
	mi := &file_proto_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsRequest) ProtoMessage() {}

func (x *UserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsRequest.ProtoReflect.Descriptor instead.
func (*UserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *UserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderStat           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsResponse) Reset() {
	*x = UserStatsResponse{}
	mi := &file_proto_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsResponse) ProtoMessage() {}

func (x *UserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsResponse.ProtoReflect.Descriptor instead.
func (*UserStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatsResponse) GetOrders() []*OrderStat {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStat) Reset() {
	*x = OrderStat{}
	mi := &file_proto_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStat) ProtoMessage() {}

func (x *OrderStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStat.ProtoReflect.Descriptor instead.
func (*OrderStat) Descriptor() ([]byte, []int) {
	return file_proto_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *OrderStat) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderStat) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_statistics_proto protoreflect.FileDescriptor

const file_proto_statistics_proto_rawDesc = "" +
	"\n" +
	"\x16proto/statistics.proto\x12\n" +
	"statistics\"+\n" +
	"\x10UserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x11UserStatsResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.statistics.OrderStatR\x06orders\"^\n" +
	"\tOrderStat\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt2e\n" +
	"\x11StatisticsService\x12P\n" +
	"\x11GetUserOrderStats\x12\x1c.statistics.UserStatsRequest\x1a\x1d.statistics.UserStatsResponseB'Z%statistics_service/proto/statisticspbb\x06proto3"

var (
	file_proto_statistics_proto_rawDescOnce sync.Once
	file_proto_statistics_proto_rawDescData []byte
)

func file_proto_statistics_proto_rawDescGZIP() []byte {
	file_proto_statistics_proto_rawDescOnce.Do(func() {
		file_proto_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_statistics_proto_rawDesc), len(file_proto_statistics_proto_rawDesc)))
	})
	return file_proto_statistics_proto_rawDescData
}

var file_proto_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_statistics_proto_goTypes = []any{
	(*UserStatsRequest)(nil),  // 0: statistics.UserStatsRequest
	(*UserStatsResponse)(nil), // 1: statistics.UserStatsResponse
	(*OrderStat)(nil),         // 2: statistics.OrderStat
}
var file_proto_statistics_proto_depIdxs = []int32{
	2, // 0: statistics.UserStatsResponse.orders:type_name -> statistics.OrderStat
	0, // 1: statistics.StatisticsService.GetUserOrderStats:input_type -> statistics.UserStatsRequest
	1, // 2: statistics.StatisticsService.GetUserOrderStats:output_type -> statistics.UserStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_statistics_proto_init() }
func file_proto_statistics_proto_init() {
	if File_proto_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_statistics_proto_rawDesc), len(file_proto_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_statistics_proto_goTypes,
		DependencyIndexes: file_proto_statistics_proto_depIdxs,
		MessageInfos:      file_proto_statistics_proto_msgTypes,
	}.Build()
	File_proto_statistics_proto = out.File
	file_proto_statistics_proto_goTypes = nil
	file_proto_statistics_proto_depIdxs = nil
}
